### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by Zorklis** [Corosauce/WATUT#1]
Since I know many people would want it

**Comment by Birbatiel** [comment]
I cannot agree more, would fit very well with all the fabric vanilla enhancement mods.

**Comment by Corosauce** [comment]
👍 
https://www.curseforge.com/minecraft/mc-mods/what-are-they-up-to/files/4989897
https://modrinth.com/mod/what-are-they-up-to/version/1.20.1-1.0.12
