### ISSUE TITLE
How can I make my GUI compatible with third-party mods?

### ISSUE THREAD

**Issue by zoe-may** [Corosauce/WATUT#13]
title

**Comment by Corosauce** [comment]
Long term plan is to implement a system that makes a tiny copy of what the client player screen is rendering, to then transmit to everyone else, so manual compatibility wont be required. If that plan fails for any reason, other avenues of compatibility might need to be explored.

**Comment by zoe-may** [comment]
Sorry if this is interrupting, but I just wanted to check on the progress of this feature.
