### ISSUE TITLE
Confliction with Optifine

### ISSUE THREAD

**Issue by Keoni2008** [Corosauce/WATUT#15]
Every time I launch Minecraft 1.19.2 with Optifine, and What are they up to the game crashes. I've tried every combination and yes I'm using CronoUtil and it still crashes. CronoUtil doesn't crash it cuz if I have only that on with Optifine it runs fine.  Each time it crashes the launcher gives me this error: 

**To Reproduce**
Probably just run Minecraft with Optifine and What are they up to. 

**latest.log, debug.log or crash report if the other 2 arent possible**
If there is a crash, add one or your issue will likely get closed for lacking enough info.

**Expected behavior**
![Screenshot 2024-01-29 190237](https://github.com/Corosauce/WATUT/assets/114753512/dc7a8055-d614-4b9c-932a-86ae2bf1ed70)

The game starts to run and then closes and redirects you to the Minecraft launcher

**Screenshots**
![Screenshot 2024-01-29 190237](https://github.com/Corosauce/WATUT/assets/114753512/eec9f0a1-0f9e-461a-8ad8-870ff524423f)

**Mod and Minecraft version:**
Game version: 1.19.2

What are they up to version: 1.19.2-1.0.14

Optifine version: 1.19.2_HD_U_H9

CronoUtil version: 1.19.2-1.3.6

**Comment by Corosauce** [comment]
Replace optifine with embeddium/rubidium and oculus for shader support.
