### ISSUE TITLE
incorrect visual when when you are typing on a sign

### ISSUE THREAD

**Issue by peow** [Corosauce/WATUT#16]
when you type on a sign, hanging sign or a book it will show that you are in the inventory GUI, which doesn't make much sense, it would be more interesting if it showed that you were typing, or at least didn't show anything
![2024-02-03_22 35 43](https://github.com/Corosauce/WATUT/assets/105888751/b6fd6a2b-3052-43fd-87da-6eaf3b51bd64)

![2024-02-03_22 36 13](https://github.com/Corosauce/WATUT/assets/105888751/df53de23-5dd7-4428-87e6-fe25259ed295)

**Comment by Corosauce** [comment]
Ohhh show typing while in a sign or book, didn't think of that even while watching new QSMP xD. Great suggestion. 

As for more GUI support: Long term plan is to implement a system that makes a tiny copy of what the client player screen is rendering, to then transmit to everyone else, so manual compatibility wont be required. If that plan fails for any reason, other avenues of compatibility might need to be explored.

I might hammer out more vanilla GUI support if I'm not able to get to the long term plan any time soon.

**Comment by peow** [comment]
I was surprised to see your mod on QSMP, did they contact you or was it a surprise for you too?

**Comment by Corosauce** [comment]
Was a surprise to me too, they didn't contact me. I've fixed these issues now in v1.1.0 as well.

**Comment by peow** [comment]
thanks
