### ISSUE TITLE
Configuration toggle for individual Gui categories

### ISSUE THREAD

**Issue by Typhonidite** [Corosauce/WATUT#17]
In my particular case, the "typing" animation conflicts with some emote mods I have. I'd like to disable it, so that the emote is not obscured by WATUT's text display that is rendered in front of the player. My suggestion is a toggle for certain categories, e.g. "typing," "inventory," "pause screen," etc. Though, I'm sure there's a better solution.

**Comment by Corosauce** [comment]
In v1.1.0 you can now more fine tune disable what you need, I separated it into 3 categories, idle, typing, gui, and for each of those you can disable either the animations or the visual indicator. For your case, set showPlayerActiveChatGui and showPlayerAnimation_Typing to false.

**Comment by DoloSaber** [comment]
> 在 v1.1.0 中，您现在可以对需要的内容进行更精细的调整，我将其分为 3 个类别，空闲、键入、gui，对于每个类别，您都可以禁用动画或视觉指示器。对于您的情况，请将 showPlayerActiveChatGui 和 showPlayerAnimation_Typing 设置为 false。

Is it possible to do a more detailed configuration?
For example, disabling animations by mods, or a configured interaction interface.
