### ISSUE TITLE
how to change this message?

### ISSUE THREAD

**Issue by peow** [Corosauce/WATUT#18]
when someone is typing this text appears:
![image](https://github.com/Corosauce/WATUT/assets/105888751/926538ce-8439-4c5c-aeff-d5262d4d033b)

i wanna to configure this to put in another language, in wich file is the configuration located?
![image](https://github.com/Corosauce/WATUT/assets/105888751/cb7916b6-5529-4e26-bbd3-b0f010fcc69f)

**Comment by Corosauce** [comment]
Added config support for this for next release.
