### ISSUE TITLE
Crash at startup after update

### ISSUE THREAD

**Issue by mateuszklysz** [Corosauce/WATUT#20]
**Describe the bug**
After updating `What Are They Up To` to the latest version `1.1.0`, the game does not start.

**To Reproduce**
1. Update Watut to `1.20.1-1.1.0` version
2. Start Minecraft

**latest.log, debug.log or crash report if the other 2 arent possible**
[crash-2024-02-12_16.08.54-client.txt](https://github.com/Corosauce/WATUT/files/14239926/crash-2024-02-12_16.08.54-client.txt)

**Expected behavior**
The game should work - checked after a downgrade of the mod, there is no problem launching Minecraft.

**Mod and Minecraft version:**
- Fabric 1.20.1
- What Are They Up To (Watut) 1.20.1-1.1.0
- CoroUtil 1.20.1-1.3.5

**Comment by ZiLenTz** [comment]
same with server startup.

log (line 857): https://mclo.gs/fOtuTJu
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'watut'!

- Fabric 0.15.6
- Minecraft 1.20.1
- Watut 1.1.0

**Comment by Corosauce** [comment]
Fixed with coroutil-fabric-1.20.1-1.3.7.jar which is being pushed to curse right now.
