### ISSUE TITLE
[1.20.1Fabric]Launch Game Crashed.

### ISSUE THREAD

**Issue by OcrSu** [Corosauce/WATUT#23]
Game Crashed When Launching the game.

CrashLog:
[crash-2024-02-15_12.17.24-client.txt](https://github.com/Corosauce/WATUT/files/14303066/crash-2024-02-15_12.17.24-client.txt)

**Mod and Minecraft version:**
What Are They Up To 1.20.1-1.1.0
MineCraft1.20.1-Fabric 0.15.6
Java21

**Comment by Mozork01** [comment]
Hello. Try with the new update of the mod coroutil-fabric-1.20.1-1.3.7.jar.
I haven't tried it, but it might work now.

**Comment by OcrSu** [comment]
> coroutil

ts.
It is indeed because the coroutil mod was not upgraded to the latest version.
Modirinth APP on my computer is not showing mods updates lately, i.e. the mod update function is not working.
