### ISSUE TITLE
1.19.2 Forge Optifine game crashes

### ISSUE THREAD

**Issue by 0BANka** [Corosauce/WATUT#27]
**Describe the bug**
I installed this mod for version 1.19.2 and coroutil on my build with optifine and the game crashes

**Mod and Minecraft version:**
Without this your issue will likely get closed for lacking enough info.
 - Version: 1.19.2 Forge
[crash.txt](https://github.com/Corosauce/WATUT/files/14474308/crash.txt)

**Comment by Corosauce** [comment]
Remove optifine and use rubidium and oculus.
