### ISSUE TITLE
Crash 1.19.2

### ISSUE THREAD

**Issue by iamdeepanshugarg** [Corosauce/WATUT#28]
**Describe the bug**
Minecraft Forge 1.19.2 Crash

**latest.log, debug.log or crash report if the other 2 arent possible**
[https://mclo.gs/IG1t635]

**Mod and Minecraft version:**
Without this your issue will likely get closed for lacking enough info.
 - Version: Forge1.19.2 WATUT-v1.0.14

**Comment by Corosauce** [comment]
remove optifine, replace with embeddium and oculus
