### ISSUE TITLE
error crash confict JEI, Dynamic Trees and First person mod

### ISSUE THREAD

**Issue by FF101UALviv** [Corosauce/WATUT#30]
[crash-2024-03-27_19.11.56-client.txt](https://github.com/Corosauce/WATUT/files/14776976/crash-2024-03-27_19.11.56-client.txt)
[crash-2024-03-27_19.12.58-client.txt](https://github.com/Corosauce/WATUT/files/14776977/crash-2024-03-27_19.12.58-client.txt)
[crash-2024-03-27_19.08.40-client.txt](https://github.com/Corosauce/WATUT/files/14776978/crash-2024-03-27_19.08.40-client.txt)

**Comment by Corosauce** [comment]
remove optifine, replace with embeddium and oculus
