### ISSUE TITLE
Crash at startup after update (FORGE)

### ISSUE THREAD

**Issue by ReineCloud** [Corosauce/WATUT#31]
**Describe the bug**
After Installing the latest version of `What Are They Up To`, version `1.1.0`, game does not start

**To Reproduce**

1. Install `What Are They Up To 1.1.0`
2. Put into .minecraft mods folder
3. Start Minecraft

**latest.log, debug.log or crash report if the other 2 arent possible**
Just gives an exit code

**Expected behavior**
The mod should work and Minecraft opens without problem (This is the same as with the older versions of the mod)

**Screenshots**
![image](https://github.com/Corosauce/WATUT/assets/88179555/5d7f91e5-ebe1-4523-82ec-e69149f8a064)

**Mod and Minecraft version:**

-  Forge 47.2.0 - 1.20.1
- What Are They Up To (Watut) 1.20.1-1.1.0
- CoroUtil 1.20.1-1.3.7

**Comment by vinnyg0621** [comment]
i'm having the same problem.

**Comment by Corosauce** [comment]
Can't help without a log, latest works fine for me.
