### ISSUE TITLE
What % blur is used for the textures?

### ISSUE THREAD

**Issue by Grass69z** [Corosauce/WATUT#35]
I would like to change the textures to fix a resource pack I'm using, so could you please provide what % of blur is used, so I can personalize my own?

**Comment by Corosauce** [comment]
Ah, saved this info for future self so itll help here, i use gimp for the blur so these values are relevant to it.

The first few ones I did I went all out with 3 different versions, but the later additions are just a single texture and 1 blur amount, heres the notes I had made about it:

darkening guis by -66 brightness in gimp
blur scales
0.5
0.75
1.5

for single texture method:
blur by 0.75, thats it
