### ISSUE TITLE
Gui being left behind while player teleported away

### ISSUE THREAD

**Issue by KelvinZhang512** [Corosauce/WATUT#4]
1, Open the Journey Map mod.
2, Select a waypoint and teleport away.
3, Other people can see a gui be left at the previous position.
![IMG_20231217_155155](https://github.com/Corosauce/WATUT/assets/48343945/a56d277a-2390-4b39-a26e-2db728f25f0f)

**Comment by Corosauce** [comment]
What version of watut?

**Comment by KelvinZhang512** [comment]
We're using 1.0.11 for Forge 1.20.1.

**Comment by Corosauce** [comment]
Ah! Reproduced it when I used it going to a different dimension. Some recent changes must have re introduced this bug. It will be fixed in the next release.

**Comment by Corosauce** [comment]
Fixed in latest.
