### ISSUE TITLE
Hand Placement Bug with Two-Handed Weapons and Torches in Mod Combination

### ISSUE THREAD

**Issue by HeyRicar** [Corosauce/WATUT#6]
When attempting to combine it with other mods such as Better Combat or Not Enough Animations, there are bugs with the hands. For instance, when holding a two-handed weapon, the character's hands may intersect with the head, and the same issue occurs when holding a torch. It's unfortunate that this occurs because these mods blend seamlessly and enhance the game's immersion. However, the current bug disrupts the otherwise cohesive experience.

**Comment by Corosauce** [comment]
👍 At some point I will be making a config that supports adding items/tags/modids to a filter that disables the animations when those items are being held.

**Comment by Corosauce** [comment]
Fixed for next release with the new config system and some default configs for mod compatibility. Better Combat doesnt ship with two handed weapons but with the new config, any mods that support those will be able to be configured to not look as jank.
